### ISSUE TITLE
ddpg tensorflow error

### ISSUE THREAD

**Issue by csianglim** [Phylliade/vinci#1]
I'm trying to run vinci's ddpg on a custom gym environment for a continuous control problem but I'm getting this error:

`ValueError: Cannot feed value of shape (1,) for Tensor 'state:0', which has shape '(?, 1)'`

The gym environment I'm using is available here (available as pip package) https://github.com/csianglim/control-gym/blob/master/gym_control/envs/control_env.py

And I'm using the vinci ddpg sample code provided in rl/tests:

````python
from rl.agents.ddpg import DDPGAgent
from rl.memory import SimpleMemory
from rl.random import OrnsteinUhlenbeckProcess
from rl.utils.networks import simple_actor, simple_critic
import gym
import gym_control
from rl.utils.env import populate_env

# Get the environment
# And populate it with useful metadata
ENV_NAME = 'Control-v0'
env = populate_env(gym.make(ENV_NAME))

# Build the actor and the critic
actor = simple_actor(env)
critic = simple_critic(env)

# Memory
memory = SimpleMemory(env=env, limit=1000000)

# Noise
random_process = OrnsteinUhlenbeckProcess(
    size=env.action_space.dim, theta=.15, mu=0., sigma=3.)

# Agent
agent = DDPGAgent(
    actor=actor,
    critic=critic,
    env=env,
    memory=memory,
    random_process=random_process,
    invert_gradients=True
)
agent.compile()

agent.train(
    env=env,
    nb_episodes=1,
    visualize=False,
    verbose=2,
    nb_max_episode_steps=200,
    plots=False)
````

Any thoughts? Do I need to change the way I'm writing my environment? I tried to compare it with Continuous Mountain Car but couldn't figure out the problem.

**Comment by Phylliade** [comment]
Hi csianglim,
By quickly looking at your env, I would say it's because it's returning observations as scalars.
the common format for observations is a vector (e.g. an array of dim 1). (It's also the same for gym envs)

So you should remove the `np.asscalar` calls.

**Comment by csianglim** [comment]
That fixed the problem, thanks!
